version: '3'

services:
  radiometer-frontend:
    image: cr.yandex/crpfcpvoap78esunmram/radiometer-frontend
    ports:
      - "8081:3000"
    environment:
      - HTTPS=true
    volumes:
      - ./conf.d/https/:/https/