FROM node:16-alpine

WORKDIR .

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build

RUN npm install -g serve

RUN mkdir -p /certs
RUN touch /certs/ssl_cert.pem
RUN touch /certs/ssl_key.pem

EXPOSE 5000

CMD ["npx", "serve", "-s", "build", "--ssl-cert", "/certs/ssl_cert.pem", "--ssl-key", "/certs/ssl_key.pem"]