version: '3'

services:
  radiometer-frontend:
    image: cr.yandex/crpfcpvoap78esunmram/radiometer-frontend
    ports:
      - "8082:3000"
    environment:
      - HTTPS=true
    volumes:
      - ./conf.d/https/fullchain.pem:/certs/ssl_cert.pem
      - ./conf.d/https/privkey.pem:/certs/ssl_key.pem