version: '3.8'

services:
  react-app:
    container_name: reactapptest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
      - "8081:443"
    environment:
      - HTTPS=true
    volumes:
      - ~/.aspnet/https:/https:ro
    stdin_open: true
    tty: true

