export const AppRoutes = {
    Main: '/',
    SignIn: '/login',
    Measurements: '/measurements',
    Measurement: (id: number | string) => `/measurements/${id}`,
    AddMeasurement: 'add-measurement',
    Devices: '/devices',
    Device: (id: number | string) => `/devices/${id}`,
    AddDevice: '/add-device',
    EditDevice: (id: number | string) => `/devices/edit/${id}`,
    Calibration: (id: number | string) => `/calibrations/${id}`,
    AddCalibration: (id: number | string) => `/calibrations/add/${id}`,
    EditCalibration: (id: number | string) => `/calibrations/edit/${id}`,
    Patients: '/patients',
    Patient: (id: number | string) => `/patients/${id}`,
    AddPatient: '/add-patient',
    EditPatient: (id: number | string) => `/patients/edit/${id}`,
    Users: '/users',
    User: (id: number | string) => `/users/${id}`,
    AddUser: '/add-user',
    EditUser: (id: number | string) => `/users/edit/${id}`,
    Logs: '/logs',
    Log: (id: string) => `/logs/${id}`,
    Tokens: '/tokens',
    Token: (id: number | string) => `/tokens/${id}`,
    AddToken: '/add-token',
    EditToken: (id: number | string) => `/tokens/edit/${id}`,
    NotFound: '*'
} as const;
