export const ApiRoutes = {
    Login: '/login',
    CheckAuth: '/checkAuth',
    Measurements: '/measurements',
    Devices: '/devices',
    AddDevice: '/add-device',
    UpdateDevice: '/update-device',
    DeleteDevice: '/delete-device',
    Calibrations: '/calibrations',
    AddCalibration: '/add-calibration',
    UpdateCalibration: '/update-calibration',
    DeleteCalibration: '/delete-calibration',
    Patients: '/patients',
    AddPatient: '/add-patient',
    UpdatePatient: '/update-patient',
    DeletePatient: '/delete-patient',
    Users: '/users',
    UsersData: '/users-data',
    AddUser: '/add-user',
    UpdateUser: '/update-user',
    UpdateUserPassword: '/update-user-password',
    DeleteUser: '/delete-user',
    Logs: '/logs',
    Tokens: '/tokens',
    AddToken: '/add-token',
    UpdateToken: '/update-token',
    DeleteToken: '/delete-token',
} as const;
