export const ApiRoutes = {
    Login: '/login',
    CheckAuth: '/checkAuth',
    Devices: '/devices',
    Patients: '/patients',
    AddPatient: '/add-patient',
    UpdatePatient: '/update-patient',
    DeletePatient: '/delete-patient',
    Users: '/users',
    AddUser: '/add-user',
    UpdateUser: '/update-user',
    UpdateUserPassword: '/update-user-password',
    DeleteUser: '/delete-user',
    Logs: '/logs',
    Tokens: '/tokens',
    AddToken: '/add-token',
    UpdateToken: '/update-token',
    DeleteToken: '/delete-token',
    Measurements: '/measurements',
} as const;
